/* Main.c file generated by New Project wizard
 *
 * Created:   sex ago 13 2021
 * Processor: PIC18F4550
 * Compiler:  MPLAB XC8
 */
#include "display.h"

void lcdInit(){
  OpenXLCD(FOUR_BIT & LINES_5X7);
  WriteCmdXLCD(0x01);
  __delay_ms(2);
}

void lcdWrite(int pos, char* str){
  WriteCmdXLCD(pos);
  putrsXLCD(str);  
}